# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

scrape_configs:
  - job_name: 'nomad_metrics'

    consul_sd_configs:
    - server: 'localhost:8500'
      services: ['nomad-client', 'nomad']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '(.*)http(.*)'
      action: keep

    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
