---
name: Backport Assistant Runner

on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.4.1
    steps:
      - name: Backport changes to stable-website
        run: |
          backport-assistant backport -merge-method=squash
        env:
          BACKPORT_LABEL_REGEXP: "backport/(?P<target>website)"
          BACKPORT_TARGET_TEMPLATE: "stable-{{.target}}"
          # Enabling this option increased the number of backport failures.
          BACKPORT_MERGE_COMMIT: false
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
      - name: Backport changes to targeted release branch
        run: |
          backport-assistant backport -merge-method=squash
        env:
          BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+\\.[+\\w]+)"
          BACKPORT_TARGET_TEMPLATE: "release/{{.target}}"
          # Enabling this option increased the number of backport failures.
          BACKPORT_MERGE_COMMIT: false
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          ENABLE_VERSION_MANIFESTS: true
          BACKPORT_LABEL_TEMPLATE: "backport/{{.ent}}{{.target}}+ent"
  backport-ent:
    if: github.event.pull_request.merged && contains(join(github.event.pull_request.labels.*.name), 'backport/ent')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backport for Enterprise
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          repository: hashicorp/nomad-enterprise
          event-type: ent-backport
          client-payload: ${{ toJson(github.event) }}
  handle-failure:
    needs:
      - backport
      - backport-ent
    if: always() && (needs.backport.result == 'failure' || needs.backport-ent.result == 'failure')
    runs-on: ${{ endsWith(github.repository, '-enterprise') && fromJSON('["self-hosted", "ondemand", "linux"]') || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/vault-secrets
        with:
          paths: |-
            kv/data/teams/nomad/slack-webhooks feed-nomad | SLACK_FEED_NOMAD ;
      - name: Send slack notification on failure
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          payload: |
            {
              "text": ":x::arrow_right_hook::nomad-sob: Backport run *FAILED*",
              "attachments": [
                {
                  "color": "#C41E3A",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Pull Request:*\n<${{ github.event.pull_request.html_url}}|${{ github.repository }}#${{ github.event.pull_request.number}}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*From:*\n@${{ github.event.sender.login }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_FEED_NOMAD || secrets.BACKPORT_ASSISTANT_FAILURE_SLACK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
permissions:
  contents: read
  id-token: write
