name: HashiCorp PR Bot

on: [pull_request]

jobs:
  check_links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./website
        run: npm install
      - name: Check Links
        uses: ./.github/actions/check_links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          baseUrl: ${{ github.event.deployment.payload.environment_url }}
